# Generated by Django 3.2.9 on 2021-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Political', 'Political'), ('Religion', 'Religion'), ('Fictions', 'Fictions'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Literature', 'Literature'), ('Actions', 'Actions')], default='Fiction', max_length=100),
        ),
    ]
