# Generated by Django 3.2.9 on 2021-11-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Political', 'Political'), ('Religion', 'Religion'), ('Fictions', 'Fictions'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Literature', 'Literature'), ('Actions', 'Actions')], default='Fiction', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default='Description'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='catalog.book'),
        ),
    ]
