# Generated by Django 3.2.9 on 2021-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20211123_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Reserved', 'Reserved'), ('Available', 'Available')], default='Unavailable', max_length=100),
        ),
    ]
